### ISSUE TITLE
test_spec_handlebars_parser 62 segfaults on ppc64le (Alpine Linux)

### ISSUE THREAD

**Issue by jirutka** [jbboehr/handlebars.c#67]
```
FAIL: test_spec_handlebars_parser 62 - test_spec_handlebars_parser.c:Handlebars Parser Spec:handlebars_spec_parser:
Received signal 11 (Segmentation fault)
```

* **Versions:**
    * handlebars.c 0.6.4
    * mustache-spec 1.1.3
    * handlebars-spec 4.0.5-p1
    * gcc 6.4.0
* **Configure options:**
    * --disable-refcounting
* **Extra CFLAGS:**
    * -Os -fomit-frame-pointer

**Complete build log:** [handlebars-0.6.4-ppc64le.log.txt](https://github.com/jbboehr/handlebars.c/files/1165366/handlebars-0.6.4-ppc64le.log.txt)

/cc @rvalle, @leitao

**Comment by leitao** [comment]
Thanks @jirutka I will take a look at it!

**Comment by rvalle** [comment]
I am not very sure what the process is here for releasing a new version.

I presume a new tag, and update push to alpine/aports is required?

maybe @jirutka can suggest?

once I have this clear I can try to setup a continuous delivery mechanism so that new releases test/trigger a pull request to aports...

**Comment by jirutka** [comment]
I’m gonna backport just the patch for now.

**Comment by jirutka** [comment]
Tests passed, thanks for the fix!
