### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by ericflickner** [jbboehr/handlebars.c#73]
I see windows support listed in the recent commits, but no install/compile instructions anywhere.  Can you update any doc w/ that?

**Comment by jbboehr** [comment]
@ericflickner You can see how it's built in the `.appveyor.yml` and `.appveyor.bat`. There are published build artifacts on the [appveyor project page](https://ci.appveyor.com/project/jbboehr/handlebars-c). It required (at the time I tested it at least) patched versions of `talloc` and `json-c`, which you can observe in the appveyor files.

Setting up the environment correctly and consistently is difficult due to differences between Windows, Windows SDK, and Visual Studio versions, and a lack of a decent package manager. Unfortunately, from what I can tell, nuget and chocolatey are not suitable for packaging native C libraries, the former focusing on C# and the latter on fully built applications.

If you are building under Cygwin, WSL, or MinGW/MSYS, I believe the process will be more like Linux.

**Comment by jbboehr** [comment]
I've dropped semi-official support for windows due to poor C library support, finicky build systems, and having switched all of my PCs to linux. Perhaps someone interested in windows support can implement it again at some point.
